package Oops.Access;

//java lang do contains the Object class
//Object class are by default inherited internally, means two extend we are doing

public class ObjectDemo {
    int num;

    //these functions are already defined intenally in Object class
   
   
    @Override
    public int hashCode(){
        return super.hashCode();
    }
    // It basically gives a number representation of an object

    @Override
    public boolean equals(Object obj){
        return super.equals(obj);
    }

    @Override
    protected Object clone() throws CloneNotSupportedException{
        return super.clone();
    }

    @Override
    public String toString(){
        return super.toString();
    }

    @Override
    protected void finalize() throws Throwable{
        super.finalize();
    }

    public ObjectDemo(int num){
        this.num=num;
    }

    public static void main(String[] args) {
        ObjectDemo obj=new ObjectDemo(34);
        System.out.println(obj.hashCode());
        //hashcode means unique representation of object via number, every object is different;
        // hashcode is not a address value, it a random integer, generated by the integer

        // we can use hashcode, to check whether the tow object are same or not

        //we can modify those
        System.out.println(obj instanceof Object);
    }
}
